//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

/// <summary>
/// This class is the structure for responses returned by the Lucene Engine
/// </summary>
public class Response
{
	//Default answer when no answer, or no net is detected
	public static string NoAnswer = "Oops! I haven’t learned that yet. But did you know: ";
	public static string NoAnswer_es = "Oops! Todav"+'\u00ED'+"a no lo he aprendido. Pero sab"+'\u00ED'+"as que: ";
	
	public static string NoNet = "It appears we've lost contact with Houston. Please connect to the internet to download latest mission updates!";
	public static string NoNet_es = "Parece que hemos perdido el contacto con Houston. Por favor, conectarse a Internet!";
	
	public static string NoQuestionEntered = "It looks like you tried to ask me a blank question. Make sure to enter your question in the field and then click the search button to the right.";
	public static string NoQuestionEntered_es = "Parece que se trat"+'\u00F3'+" de hacerme una pregunta en blanco. Aseg"+'\u00FA'+"rese de introducir su pregunta en el campo y haga clic en la flecha hacia la derecha.";
	
	public static string tierTwo = "If you were asking ";
	public static string tierTwo_es = "Si preguntaras ";
	
	public static string tierThree = "Sorry, I don't understand. Did you mean to ask: ";
	public static string tierThree_es = "Lo siento, no entiendo. Quer"+'\u00ED'+"as "+ "decir: ";
	
	public static string tierFour = "Oops! I haven’t learned that yet. But did you know: ";
	public static string tierFour_es = "Lo siento, no tengo la respuesta para esa pregunta. Trabajar"+'\u00E1'+"n mis expertos en eso.";
	
	//Default constructor	
	public Response(){}
	
	
	public Response(string q, int qId, int qIdSug1, int qIdSug2, string a, int aId, int tier, double queryScore,  double queryScoreSug1,  double queryScoreSug2, int organicFlag)
	{
		question = q;
		question_id = qId;
		answer = a;
		answer_id = aId;
		question_id_sug1 = qIdSug1;
		question_id_sug2 = qIdSug2;
		qtier = tier;
		qscore = queryScore;
		qscore_sug1 = queryScoreSug1;
		qscore_sug2 = queryScoreSug2;
		qorganic = organicFlag;
	}
	
	public string question { get; set; }
	public int question_id { get; set; }
	public string answer { get; set; }
	public int answer_id { get; set; }
	public int question_id_sug1 { get; set; }
	public int question_id_sug2 { get; set; }
	public int qtier { get; set; }
	public double qscore { get; set; }
	public double qscore_sug1 { get; set; }
	public double qscore_sug2 { get; set; }
	public int qorganic { get; set; }
}
